name: easy_observable
description: An easy-to-use observability library for Flutter.
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.8.0
  rxdart:
  context_watch:
    git:
      url: git@github.com:s0nerik/context_watch.git
      ref: 28120ad1503f88f2dee5487388a305e2b931251e

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  vm_service:
  test:
  benchmarking: ^0.6.1

flutter:
