name: easy_observable
description: An easy-to-use observability library for Flutter.
version: 0.0.1

environment:
  sdk: '>=2.19.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  weak_map: ^2.1.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  vm_service:
  test:
  benchmarking: ^0.6.1

flutter:
